services:
    form.type.tags:
        class: BSP\TagBundle\Form\Type\TagsType
        tags:
            - { name: form.type, alias: tags }

    form.type.hidden_tags:
        class: BSP\TagBundle\Form\Type\HiddenTagsType
        tags:
            - { name: form.type, alias: hidden_tags }
